return {
	BlackburnSounds = {
		files = {
			"halloween_abominationexplosion.ogg",
			"halloween_werewolf_alfawolf.ogg",
			"halloween_werewolf_minormoans.ogg",
			"halloween_werewolf_transformation.ogg",
			"kr_ambience_cb_aquelarre.ogg",
			"kr_ambience_cb_ghosts_1.ogg",
			"kr_sfx_cb_crow.ogg",
			"kr_sfx_cb_giantrats1.ogg",
			"kr_sfx_cb_giantrats2.ogg",
			"kr_sfx_cb_lordblackburn_death.ogg",
			"kr_sfx_cb_lordblackburn_specialstomp.ogg",
			"kr_sfx_cb_lordblackburn_swing.ogg",
			"kr_sfx_cb_nessie.ogg",
			"kr_sfx_cb_witch_fast.ogg",
			"kr_sfx_cb_witch_slow.ogg",
			"kr_sfx_cb_witchdeath.ogg"
		}
	},
	ElvesLevelHRSounds = {
		append = true,
		files = {
			"GalhadriansBastion-01c.ogg",
			"GalhadriansBastion-02c.ogg"
		}
	},
	AmazonSounds = {
		files = {
			"amazon_taunt_1.ogg",
			"amazon_taunt_2.ogg"
		}
	},
	HalloweenSounds = {
		files = {
			"halloween_abominationexplosion.ogg",
			"halloween_werewolf_alfawolf.ogg",
			"halloween_werewolf_minormoans.ogg",
			"halloween_werewolf_transformation.ogg"
		}
	},
		HWFrankensteinTower = {
		files = {
			"FrankyTower-01d.ogg",
			"FrankyTower-02f.ogg",
			"FrankyTower-03c.ogg",
			"FrankyTower-04a.ogg",
			"Sound_Tesla_attack_1.ogg",
			"Sound_Tesla_attack_2.ogg",
			"halloween_tesla_charge.ogg"
		}
	},
	HeroArcher = {
		files = {
			"Aleria_special_arrow.ogg",
			"Aleria_sumon.ogg",
			"Aleria_wildcat_hit.ogg",
			"Female-Elven-Archer-01c.ogg",
			"Female-Elven-Archer-03a.ogg",
			"Female-Elven-Archer-04b.ogg",
			"Female-Elven-Archer-Death_a.ogg",
			"Level_up.ogg"
		}
	},
	HeroDenas = {
		files = {
			"KingDenas-01d.ogg",
			"KingDenas-02d.ogg",
			"KingDenas-03g.ogg",
			"KingDenas-05c.ogg",
			"KingDenas_sfx_attack.ogg",
			"KingDenas_sfx_order1.ogg",
			"KingDenas_sfx_order3.ogg",
			"Level_up.ogg"
		}
	},
	HeroFrost = {
		files = {
			"Elora_GroundFreeze.ogg",
			"Elora_IceShard.ogg",
			"Elora_IceShardBreak.ogg",
			"Elora_IceShardSummon.ogg",
			"Frost-Mage-02c.ogg",
			"Frost-Mage-03d.ogg",
			"Frost-Mage-04a.ogg",
			"Frost-Mage-Death_01c.ogg",
			"Level_up.ogg"
		}
	},
	HeroAlric = {
		files = {
			"alric_taunt_confirm_1.ogg",
			"alric_taunt_confirm_3.ogg",
			"alric_taunt_confirm_2.ogg",
			"alric_taunt_confirm_4.ogg",
			"alric_taunt_death.ogg",
			"hero_alric_flurry.ogg",
			"hero_alric_sandwarrior.ogg"
		}
	},
	HeroMage = {
		files = {
			"Level_up.ogg",
			"Mage_blue_rain_charge.ogg",
			"Mage_blue_rain_drop.ogg",
			"Mage_shadows.ogg",
			"Young-Mage-01d.ogg",
			"Young-Mage-03c.ogg",
			"Young-Mage-04c.ogg",
			"Young-Mage-Death_c.ogg"
		}
	},
	HeroPaladin = {
		files = {
			"Holy-Paladin-02c.ogg",
			"Holy-Paladin-03b.ogg",
			"Holy-Paladin-04a.ogg",
			"Holy-Paladin-Death_b.ogg",
			"Level_up.ogg",
			"Paladin_deflect.ogg",
			"Paladin_shield_buff.ogg"
		}
	},
	HeroPirate = {
		files = {
			"blackthorne_taunt_confirm_1.ogg",
			"blackthorne_taunt_confirm_2.ogg",
			"blackthorne_taunt_confirm_4.ogg",
			"blackthorne_taunt_death.ogg",
			"hero_blackthorne_barrel.ogg",
			"hero_blackthorne_kraken.ogg"
		}
	},
	HeroRainOfFire = {
		files = {
			"Cinder_special_area.ogg",
			"Cinder_special_fireball_1_start.ogg",
			"Cinder_special_fireball_2_end.ogg",
			"Elemental-02c.ogg",
			"Elemental-03b.ogg",
			"Elemental-04c.ogg",
			"Elemental-Death_c.ogg",
			"Level_up.ogg",
			"Motumbo_hit.ogg"
		}
	},
	HeroReinforcement = {
		files = {
			"Level_up.ogg",
			"Motumbo_charge_special.ogg",
			"Motumbo_hit.ogg",
			"Motumbo_jump_special.ogg",
			"Reinforcement-02c.ogg",
			"Reinforcement-03c.ogg",
			"Reinforcement-04b.ogg",
			"Reinforcement-Death_c.ogg"
		}
	},
	HeroRifleman = {
		files = {
			"Dwarf-Rifleman-02c.ogg",
			"Dwarf-Rifleman-03c.ogg",
			"Dwarf-Rifleman-04c.ogg",
			"Dwarf-Rifleman-Death_c.ogg",
			"Dwarf_brea_shot2.ogg",
			"Dwarf_brea_shot_hit.ogg",
			"Dwarf_mine.ogg",
			"Level_up.ogg"
		}
	},
	HeroRobot = {
		files = {
			"Hacksaw-02c.ogg",
			"Hacksaw-03a.ogg",
			"Hacksaw-04a.ogg",
			"Hacksaw-Death01c.ogg",
			"Level_up.ogg",
			"inferno_lumberjack_drill.ogg",
			"inferno_lumberjack_shootSaw.ogg"
		}
	},
	HeroSamurai = {
		files = {
			"Level_up.ogg",
			"Oni-01c.ogg",
			"Oni-02c.ogg",
			"Oni-04a.ogg",
			"Oni-Death01a.ogg",
			"inferno_oni_groundSwords.ogg",
			"inferno_oni_instakill.ogg"
		}
	},
	ElvesCreepGolem = {
		files = {
			"kro_sfx_elemental_areaattack.ogg",
			"kro_sfx_elemental_death.ogg"
		}
	},
	HeroThor = {
		files = {
			"KR_sfx_thor_ataqueelectrico.ogg",
			"KR_sfx_thor_lanzamartillo_op2.ogg",
			"KR_sfx_thor_muerte.ogg",
			"KR_sfx_thor_thunder.ogg",
			"Level_up.ogg",
			"Thor_02a.ogg",
			"Thor_03c.ogg",
			"Thor_04c.ogg",
			"Thor_05c.ogg"
		}
	},
	HeroViking = {
		files = {
			"Level_up.ogg",
			"Viking-01b.ogg",
			"Viking-02c.ogg",
			"Viking-03b.ogg",
			"Viking-Death_01d.ogg",
			"Viking_Call.ogg",
			"Viking_Hit.ogg",
			"Viking_StartAttack.ogg",
			"Viking_Transform.ogg"
		}
	},
	InfernoSounds = {
		files = {
			"inferno_boss_death.ogg",
			"inferno_boss_horns.ogg",
			"inferno_boss_stomp.ogg"
		}
	},
	JtEffects = {
		files = {
			"Sound_EnemyJtAttack.ogg",
			"Sound_EnemyJtDeath.ogg",
			"Sound_EnemyJtEat.ogg",
			"Sound_EnemyJtExplode.ogg",
			"Sound_EnemyJtRest.ogg",
			"Sound_HitIce1.ogg",
			"Sound_HitIce2.ogg",
			"Sound_HitIce3.ogg"
		}
	},
	MushroomSounds = {
		files = {
			"KR_sfx_mushroomboss_gas_op1.ogg",
			"KR_sfx_mushroomboss_muerte.ogg",
			"KR_sfx_mushroomcreep_muerte_edit_vanzen.ogg",
			"KR_sfx_mushroomcreep_nacimiento.ogg"
		}
	},
	VeznanEffects = {
		files = {
			"Sound_DemonPortal_Summon.ogg",
			"Sound_DemonPortal_Telein.ogg",
			"Sound_EnemyVeznan_attack.ogg",
			"Sound_EnemyVeznan_death.ogg",
			"Sound_EnemyVeznan_demonFire.ogg",
			"Sound_EnemyVeznan_toDemon.ogg",
			"Sound_SpellTowerHold_Cast.ogg",
			"Sound_SpellTowerHold_Dissipate.ogg",
			"Sound_SpellTowerHold_Hit.ogg",
			"Sound_SpellTowerHold_Trap.ogg"
		}
	},
	ElvesHeroDurax = {
		files = {
			"Durax_01a[wet].ogg",
			"Durax_02a[wet].ogg",
			"Durax_03a[wet].ogg",
			"Level_up.ogg",
			"kro_sfx_durax_armblade.ogg",
			"kro_sfx_durax_crystallites.ogg",
			"kro_sfx_durax_death[op1].ogg",
			"kro_sfx_durax_lethalprism_shot_v2.ogg",
			"kro_sfx_durax_movement[loop_end].ogg",
			"kro_sfx_durax_movement[loop_op1].ogg",
			"kro_sfx_durax_movement[loop_op1].ogg",
			"kro_sfx_durax_shardspear[impact].ogg",
			"kro_sfx_durax_shardspear[throw].ogg",
			"kro_sfx_durax_ultimate.ogg"
		}
	},
	ElvesHeroPhoenix = {
		files = {
			"Level_up.ogg",
			"Phoenix2-death_01a.ogg",
			"Phoenix2-death_01a.ogg",
			"kro_sfx_phoenix_basicattack.ogg",
			"kro_sfx_phoenix_blazingoffspring_hit_v2.ogg",
			"kro_sfx_phoenix_blazingoffspring_shot[op1].ogg",
			"kro_sfx_phoenix_eggexplosion.ogg",
			"kro_sfx_phoenix_fireegg_activate_v2.ogg",
			"kro_sfx_phoenix_fireegg_v3.ogg",
			"kro_sfx_phoenix_immolation_v2.ogg",
			"kro_sfx_phoenix_ringoffire_explode_v2.ogg",
			"kro_sfx_phoenix_ringoffire_spawn[op2].ogg"
		}
	},
	ElvesHeroLilith = {
		files = {
			"Level_up.ogg",
			"Lilith_confirm-02d[wet].ogg",
			"Lilith_confirm-03f[wet].ogg",
			"Lilith_confirm-04a[wet].ogg",
			"Lilith_death-01a[wet].ogg",
			"kro_sfx_lilith_infernalwheel.ogg",
			"kro_sfx_lilith_reaperharvest.ogg",
			"kro_sfx_lilith_resurrection[op2-conchime].ogg",
			"kro_sfx_lilith_soulreaper[op1].ogg",
			"kro_sfx_lilith_ultimate[darkangels-cast].ogg",
			"kro_sfx_lilith_ultimate[darkangels-hit].ogg",
			"kro_sfx_lilith_ultimate[meteors-impact-op1_singlehit].ogg",
			"kro_sfx_veznan_range_shoot_v1.ogg"
		}
	},
	HeroWizard = {
		files = {
			"hero_nivus_attack.ogg",
			"hero_nivus_desintegrate.ogg",
			"hero_nivus_magicmissile_hit.ogg",
			"hero_nivus_magicmissile_summon.ogg",
			"hero_nivus_teleport.ogg",
			"wizzard_taunt_confirm_2.ogg",
			"wizzard_taunt_confirm_3.ogg",
			"wizzard_taunt_confirm_4.ogg",
			"wizzard_taunt_death.ogg"
		}
	},
	ElvesHeroDenas = {
		files = {
			"Eridan_Death-01a.ogg",
			"Kingsguard_01d.ogg",
			"Kingsguard_02c.ogg",
			"Level_up.ogg",
			"PrinceDenas-confirm_01a.ogg",
			"PrinceDenas-confirm_02c.ogg",
			"PrinceDenas-confirm_03b.ogg",
			"PrinceDenas-death_01a.ogg",
			"kro_sfx_princedenas_celebrity_v1[severalshots].ogg",
			"kro_sfx_princedenas_mighty_v3[convoz_op3].ogg",
			"kro_sfx_princedenas_sybarite_v1[op1].ogg",
			"kro_sfx_princedenas_wealthy_v1[op2].ogg"
		}
	},
	ElvesSpecialEwoks = {
		files = {
			"Awok_01b.ogg",
			"Awok_02c.ogg"
		}
	},
	ElvesTowerBastionSounds = {
		files = {
			"kro_sfx_bastion_shot[op1]_modif.ogg"
		}
	},
	ElvesSpecialGnome = {
		files = {
			"Gnome_01d.ogg",
			"Gnome_02a.ogg"
		}
	},
	ElvesLevelTenSounds = {
		files = {
			"kro_sfx_gnome_death[op1].ogg",
			"kro_sfx_gnome_death[op4].ogg",
			"kro_sfx_gnome_death[op7].ogg",
			"kro_sfx_simon_activate_v2.ogg",
			"kro_sfx_simon_blue_v2.ogg",
			"kro_sfx_simon_green_v2.ogg",
			"kro_sfx_simon_red_v2.ogg",
			"kro_sfx_simon_wrong_v2.ogg",
			"kro_sfx_simon_yellow_v2.ogg"
		}
	},
	ElvesGnome = {
		files = {
			"kro_sfx_gnome_desintegrate_v2[comic].ogg",
			"kro_sfx_gnome_poison_v2[confrasco].ogg",
			"kro_sfx_gnome_polymorf[conchimes].ogg",
			"kro_sfx_gnome_polymorf[conchimes].ogg",
			"kro_sfx_veznan_teleport_v1.ogg"
		}
	},
	GenieSounds = {
		files = {
			"genie_taunt_1.ogg",
			"genie_taunt_2.ogg"
		}
	},
	LegionnaireSounds = {
		files = {
			"legionnaire_taunt_1.ogg",
			"legionnaire_taunt_2.ogg"
		}
	},
	HeroMinotaur = {
		files = {
			"KRF_sfx_minotauro_ataquefuerte.ogg",
			"KRF_sfx_minotauro_carga.ogg",
			"KRF_sfx_minotauro_grito.ogg",
			"KRF_sfx_minotauro_portal.ogg",
			"KRF_sfx_minotauro_remolino_2tiempo.ogg",
			"Minotaur_01b.ogg",
			"Minotaur_02c.ogg",
			"Minotaur_03c.ogg",
			"Minotaur_05e_death.ogg"
		}
	},
	common = {
		keep = true,
		files = {
			"Arcane_Ready.ogg",
			"kro_sfx_gnome_death[op1].ogg",
			"kro_sfx_gnome_death[op4].ogg",
			"kro_sfx_gnome_death[op7].ogg",
			"kro_sfx_simon_activate_v2.ogg",
			"kro_sfx_simon_blue_v2.ogg",
			"kro_sfx_simon_green_v2.ogg",
			"kro_sfx_simon_red_v2.ogg",
			"kro_sfx_simon_wrong_v2.ogg",
			"kro_sfx_simon_yellow_v2.ogg",
			"Arcane_Taunt1.ogg",
			"Arcane_Taunt2.ogg",
			"Archer_Ready.ogg",
			"Archer_Taunt1.ogg",
			"Archer_Taunt2.ogg",
			"amazon_taunt_1.ogg",
			"genie_taunt_1.ogg",
			"genie_taunt_2.ogg",
			"legionnaire_taunt_1.ogg",
			"legionnaire_taunt_2.ogg",
			"amazon_taunt_2.ogg",
			"Artillery_Ready.ogg",
			"Artillery_Taunt1.ogg",
			"Artillery_Taunt2.ogg",
			"BFG_Ready.ogg",
			"BFG_Taunt1.ogg",
			"BFG_Taunt2.ogg",
			"Barbarian_Move.ogg",
			"Barbarian_Ready.ogg",
			"Barbarian_Taunt1.ogg",
			"Barbarian_Taunt2.ogg",
			"Barrack_Move.ogg",
			"Barrack_Ready.ogg",
			"Barrack_Taunt1.ogg",
			"Barrack_Taunt2.ogg",
			"Dwarf-Rifleman-01a.ogg",
			"Elemental-01c.ogg",
			"Elf_Taun1.ogg",
			"Sound_TowerBuilding.ogg",
			"Elf_Taun2.ogg",
			"Female-Elven-Archer-02c.ogg",
			"Frost-Mage-01a.ogg",
			"GUITransitionClose.ogg",
			"GUITransitionOpen.ogg",
			"Hacksaw-01c.ogg",
			"Holy-Paladin-01c.ogg",
			"KingDenas-04e.ogg",
			"Level_up.ogg",
			"Mage_Ready.ogg",
			"Mage_Taunt1.ogg",
			"Mage_Taunt2.ogg",
			"Muskateer_Event1.ogg",
			"Muskateer_Event2.ogg",
			"Muskateer_Ready.ogg",
			"Muskateer_Snipe.ogg",
			"Oni-03c.ogg",
			"Paladin_Move.ogg",
			"Paladin_Ready.ogg",
			"Paladin_Taunt1.ogg",
			"Paladin_Taunt2.ogg",
			"Ranger_Ready.ogg",
			"Ranger_Taunt1.ogg",
			"Ranger_Taunt2.ogg",
			"Reinforcement-01a.ogg",
			"Reinforcements_Event1.ogg",
			"Reinforcements_Event2.ogg",
			"Reinforcements_Event3.ogg",
			"Reinforcements_Event4.ogg",
			"Time_Wizard_Sandstorm2.ogg",
			"Time_Wizard_Taunt2.ogg",
			"Ancient_Guardian_1.ogg",
			"Ancient_Guardian_2.ogg",
			"Ancient_Guard_Death.ogg",
			"Sorcerer_Ready.ogg",
			"Sorcerer_Taunt1.ogg",
			"kro_sfx_bastion_shot[op1]_modif.ogg",
			"Sorcerer_Taunt2.ogg",
			"Sound_AchievementWin.ogg",
			"Sound_ArcaneDesintegrate.ogg",
			"Sound_ArrowHit2.ogg",
			"Sound_ArrowHit3.ogg",
			"Sound_ArrowRelease2.ogg",
			"Sound_ArrowRelease3.ogg",
			"Sound_BattleAxe.ogg",
			"Sound_Bomb1.ogg",
			"Sound_Chieftain.ogg",
			"Sound_Coins.ogg",
			"Sound_CommonAreaHit.ogg",
			"Sound_EnemyBigDead.ogg",
			"Sound_EnemyExplode1.ogg",
			"Sound_EnemyGoblinDead.ogg",
			"Sound_EnemyHealing.ogg",
			"Sound_EnemyOrcDead.ogg",
			"Sound_EnemyPuffDead.ogg",
			"Sound_EnemyRocketeer.ogg",
			"Sound_EnemySkeletonBreak2.ogg",
			"Sound_EnemyTrollDead.ogg",
			"Sound_EngineerShot.ogg",
			"Sound_FireballHit.ogg",
			"Sound_FireballUnleash.ogg",
			"Sound_GUIButtonCommon.ogg",
			"Sound_GUIBuyUpgrade.ogg",
			"Sound_GUIMouseOverTowerIcon.ogg",
			"Sound_GUIOpenTowerMenu.ogg",
			"Sound_HumanDead1.ogg",
			"Sound_HumanDead2.ogg",
			"Sound_HumanDead3.ogg",
			"Sound_HumanDead4.ogg",
			"Sound_JuggernautDeath.ogg",
			"Sound_LooseLife.ogg",
			"Sound_MageShot.ogg",
			"Sound_MapNewFlag.ogg",
			"Sound_MapRoad.ogg",
			"Sound_NextWaveReady.ogg",
			"Sound_NotificationClose.ogg",
			"Sound_NotificationOpen.ogg",
			"Sound_NotificationPaperOver.ogg",
			"Sound_NotificationSecondLevel.ogg",
			"Sound_PaladinHeal.ogg",
			"Sound_Polimorph.ogg",
			"Sound_QuestCompleted.ogg",
			"Sound_QuestFailed.ogg",
			"Sound_RallyPointPlaced.ogg",
			"Sound_RayArcane.ogg",
			"Sound_RockElementalDeath.ogg",
			"Sound_RockElementalRally.ogg",
			"Sound_RocketLaunt.ogg",
			"Sound_Sheep.ogg",
			"Sound_Shootgun.ogg",
			"Sound_Shrapnel.ogg",
			"Sound_Sniper.ogg",
			"GalhadriansBastion-01c.ogg",
			"GalhadriansBastion-02c.ogg",
			"Sound_Sorcerer.ogg",
			"Sound_SpellRefresh.ogg",
			"Sound_SpellSelect.ogg",
			"Sound_SpiderAttack2.ogg",
			"Sound_Teleport.ogg",
			"Sound_Tesla_attack_1.ogg",
			"Sound_Tesla_attack_2.ogg",
			"Sound_Thorn.ogg",
			"Sound_TowerBuilding.ogg",
			"Sound_TowerOpenDoor.ogg",
			"Sound_TowerSell.ogg",
			"Sound_TowerSoldierSasquashRally.ogg",
			"Sound_TowerSoldierSasquashReady.ogg",
			"Sound_WaveIncoming.ogg",
			"Sound_WinStars.ogg",
			"Sound_WolfAttack.ogg",
			"Sound_WolfAttack2.ogg",
			"Tesla_Ready.ogg",
			"Tesla_Taunt1.ogg",
			"Tesla_Taunt2a.ogg",
			"Tesla_Taunt2b.ogg",
			"Tesla_Taunt2c.ogg",
			"mecha_dropoil.ogg",
			"mecha_spawn.ogg",
			"mecha_steamrelease.ogg",
			"mecha_taunt_misc.ogg",
			"mecha_taunt_missile.ogg",
			"mecha_taunt_ready.ogg",
			"mecha_taunt_slow.ogg",
			"mecha_walk.ogg",
			"necromancer_deathknight_taunt_1.ogg",
			"necromancer_deathknight_taunt_2.ogg",
			"necromancer_attack.ogg",
			"necromancer_pestilence.ogg",
			"mecromancer_summon.ogg",
			"necromancer_taunt_ready.ogg",
			"necromancer_taunt_dknight.ogg",
			"necromancer_taunt_pesti.ogg",
			"necromancer_taunt_ready.ogg",
			"Thor_01a.ogg",
			"Viking-01b.ogg",
			"Young-Mage-02a.ogg",
			"ForestProtector_Circle[2]-01g.ogg",
			"ForestProtector_Eerie[2]-01a.ogg",
			"ForestProtector_Ancient[2]-01c.ogg",
			"ForestProtector_Ready[2]-01c.ogg",
			"kr3_sfx_forestkeeper_ancientoakspear_LOW_v1+3db.ogg",
			"kr3_sfx_forestkeeper_circleofhealing-CONGAITA_HI.ogg",
			"kr3_sfx_forestkeeper_eeriegarden_SINPOPS.ogg",
			"kr3_sfx_forestkeeper_normalspear_v2-op1.ogg",
			"halloween_bonedragon_attack.ogg",
			"halloween_bonedragon_bonerain.ogg",
			"halloween_bonedragon_kamikaze2.ogg",
			"halloween_bonedragon_respawn_simple.ogg",
			"halloween_bonedragon_soulsplague.ogg",
			"halloween_bonedragon_spawn_congrowl.ogg",
			"kro_sfx_ashbite_confirm_v1[op1].ogg",
			"kro_sfx_ashbite_confirm_v1[op2].ogg",
			"hero_dragon_death.ogg",
			"hero_dragon_flamethrower.ogg",
			"hero_dragon_smoke.ogg",
			"hero_dragon_spit.ogg",
			"Bonehart-01a_WET.ogg",
			"Bonehart-02b_WET.ogg",
			"Bonehart-03b_WET.ogg",
			"Bonehart-04c_WET.ogg",
			"templar_arterialStrike.ogg",
			"templar_holyGrail.ogg",
			"templar_taunt_ready.ogg",
			"templar_taunt_1.ogg",
			"templar_taunt_2.ogg",
			"templar_taunt_3.ogg",
			"Bladesinger_BladeDance[2]-01a.ogg",
			"Bladesinger_PerfectParry[2]-01d.ogg",
			"Bladesinger_SwirlingEdge[2]-01a.ogg",
			"Bladesinger_Ready[2]-01b.ogg",
			"KRF_sfx_vodoo_ataqueV3.ogg",
			"Vodoo_05d.ogg",
			"KRF_sfx_vodoo_kamikazegolpev3.ogg",
			"KRF_sfx_vodoo_kamikazelanza.ogg",
			"KRF_sfx_vodoo_calaveraV3_op2.ogg",
			"Vodoo_01c.ogg",
			"Vodoo_02b.ogg",
			"Vodoo_03b.ogg",
			"Vodoo_04b.ogg",
			"KRF_sfx_vodoo_munieco.ogg",
			"Veznan-confirm_01e.ogg",
			"Veznan-confirm_02f.ogg",
			"Veznan-confirm_04_custom_ec.ogg",
			"Veznan_death-[new]01b.ogg",
			"kro_sfx_veznan_arcanenova_v1.ogg",
			"kro_sfx_veznan_darkpact_v1.ogg",
			"kro_sfx_veznan_demondeath_v3.ogg",
			"kro_sfx_veznan_demonfireball_hit_v3.1.ogg",
			"kro_sfx_veznan_demonfireball_throw_v3.ogg",
			"kro_sfx_veznan_magicshackles_v1[op2]-01.ogg",
			"kro_sfx_veznan_range_shoot_v1.ogg",
			"kro_sfx_veznan_soulburn_v8[sinimpacto].ogg",
			"kro_sfx_veznan_teleport_v1.ogg",
			"Durax_04c[wet].ogg",
			"PrinceDenas-confirm_04a.ogg",
			"Lilith_confirm-01d[wet].ogg",
			"wizzard_taunt_confirm_1.ogg",
			"Minotaur_04b.ogg",
			"Drow_01c.ogg",
			"Drow_02c.ogg",
			"Drow_03b.ogg",
			"kro_sfx_faerydragon_attack[solocristalizacion].ogg",
			"kro_sfx_faerydragon_buydragon[op1].ogg",
			"kro_sfx_faerydragon_extraability[solochimes].ogg",
			"kro_sfx_faerydragon_sfx_attack[op2][soloattack]_B.ogg",
			"kr3_sfx_bladesinger_perfectparry_v2-op2-faded.ogg",
			"kr3_sfx_bladesinger_bladedance_v2-op2.ogg",
			"dwaarp_attack.ogg",
			"dwaarp_drillIn.ogg",
			"dwaarp_drillOut.ogg",
			"dwaarp_lavaSmash.ogg",
			"earthquake_taunt_ready.ogg",
			"earthquake_taunt_drill.ogg",
			"earthquake_taunt_scorched.ogg",
			"crossbow_eagle.ogg",
			"crossbow_taunt_ready.ogg",
			"crossbow_taunt_eagle.ogg",
			"crossbow_taunt_multishot.ogg",
			"archmage_twister.ogg",
			"archmage_taunt_twister.ogg",
			"archmage_taunt_ready.ogg",
			"archmage_taunt_explosion.ogg",
			"archmage_taunt_twister.ogg",
			"archmage_attack.ogg",
			"archmage_precharge.ogg",
			"axlethrower_totem_weakness.ogg",
			"axlethrower_totem_vanish.ogg",
			"axlethrower_taunt_totem2.ogg",
			"axlethrower_taunt_totem1.ogg",
			"axlethrower_taunt_ready.ogg",
			"axlethrower_totem_spirits.ogg",
			"blackthorne_taunt_death.ogg",
			"hero_blackthorne_barrel.ogg",
			"hero_blackthorne_kraken.ogg",
			"priest_taunt_confirm_1.ogg",
			"priest_taunt_confirm_2.ogg",
			"priest_taunt_confirm_3.ogg",
			"priest_taunt_confirm_4.ogg",
			"priest_taunt_confirm_5.ogg",
			"hero_priest_teleport.ogg",
			"hero_priest_healing.ogg",
			"priest_taunt_death.ogg",
			"hero_priest_consecrate.ogg",
			"archmage_explosion.ogg",
			"assassin_gold.ogg",
			"assassin_sneakattack.ogg",
			"assassin_taunt_sneak.ogg",
			"assassin_taunt_gold.ogg",
			"assassin_taunt_counter.ogg",
			"FrankyTower-01d.ogg",
			"FrankyTower-02f.ogg",
			"FrankyTower-03c.ogg",
			"FrankyTower-04a.ogg",
			"Sound_Tesla_attack_1.ogg",
			"Sound_Tesla_attack_2.ogg",
			"halloween_tesla_charge.ogg",
			"Level_up.ogg",
			"hero_dragon_fireball_explode.ogg",
			"Bonehart-Death01c_WET.ogg",
			"kro_sfx_wilbur_attack[concasquillos].ogg",
			"kro_sfx_wilbur_bombsmarch[op1].ogg",
			"kro_sfx_wilbur_boombox.ogg",
			"kro_sfx_wilbur_boombox_box.ogg",
			"Gyro_death-01d.ogg",
			"kro_sfx_wilbur_dronesattack[metralla]_cut.ogg",
			"kro_sfx_wilbur_calldrones.ogg",
			"kro_sfx_wilbur_smokespit.ogg",
			"savant_attack.ogg",
			"Dante-02a.ogg",
			"Dante-03a.ogg",
			"Dante-04d.ogg",
			"Dante-Death01c.ogg",
			"halloween_helsing_holywater_conquemadura.ogg",
			"halloween_helsing_relic.ogg",
			"Gyro_confirm-01c.ogg",
			"Gyro_confirm-02c.ogg",
			"Gyro_confirm-03c.ogg",
			"Gyro_confirm-04b.ogg",
			"alien_taunt_confirm_1.ogg",
			"alien_taunt_confirm_2.ogg",
			"alien_taunt_confirm_3.ogg",
			"alien_taunt_death.ogg",
			"hero_alien_abduction.ogg",
			"hero_alien_death_explosion.ogg",
			"hero_alien_disc_bounce.ogg",
			"hero_alien_disc_throw.ogg",
			"hero_alien_drone_call.ogg",
			"hero_alien_drone_leave.ogg",
			"hero_alien_drone_ray_loop.ogg",
			"giant_taunt_confirm_1.ogg",
			"giant_taunt_confirm_2.ogg",
			"giant_taunt_confirm_3.ogg",
			"giant_taunt_death.ogg",
			"sndFight.wav",
			"alric_taunt_confirm_1.ogg",
			"alric_taunt_confirm_3.ogg",
			"alric_taunt_confirm_2.ogg",
			"alric_taunt_confirm_4.ogg",
			"alric_taunt_death.ogg",
			"hero_alric_flurry.ogg",
			"Ninja 01b.wav",
			"Ninja 02b.wav",
			"Ninja 03b.wav",
			"Ninja 04c.wav",
			"sndFire.wav",
			"sndDragon.wav",
			"hero_alric_sandwarrior.ogg",
			"hero_grawl_bigpunch.ogg",
			"hero_grawl_boulder_hit.ogg",
			"hero_grawl_boulder_throw.ogg",
			"hero_grawl_stomp.ogg",
			"sndDeathOgr.wav",
			"Elf Archer 01b.wav",
			"Elf Archer 02c.wav",
			"Elf Archer 03c.wav",
			"Elf Archer 04b.wav",
			"twoface_destructive_cast_ends.wav",
			"inapp_atfreezeend.ogg",
			"inapp_atfreezestart.ogg",
			"Doomhammer 01a.wav",
			"Doomhammer 02c.wav",
			"Doomhammer 03d.wav",
			"Doomhammer 04b.wav",
			"nspirit_support_call.wav",
			"sndBarrel.wav",
			"Mortar 01b.wav",
			"Mortar 02a.wav",
			"Mortar 03a.wav",
			"Mortar 04c.wav",
			"Awok_01b.ogg",
			"Awok_02c.ogg",
			"Lightning Wizard 01c.wav",
			"Lightning Wizard 03a.wav",
			"Lightning Wizard 02a.wav",
			"Lightning Wizard 04a.wav",
			"inapp_cash.ogg",
			"inapp_chin.ogg",
			"inapp_freeze.ogg",
			"inapp_gems.ogg",
			"inapp_gnome.ogg",
			"inapp_hearts.ogg",
			"inapp_nuke.ogg",
			"inapp_nuke_falling.ogg",
			"dwarfArcher_taunt_1.ogg",
			"dwarfArcher_taunt_2.ogg",
			"dwarfBarracks_taunt_1.ogg",
			"dwarf_taunt_1.ogg",
			"dwarf_taunt_2.ogg",
			"pirate_taunt_1.ogg",
			"pirate_taunt_2.ogg",
			"pirate_taunt_3.ogg",
			"Pirate_Big_01c.ogg",
			"Pirate_Big_02c.ogg",
			"Pirate_Tower_01a.ogg",
			"Pirate_Tower_02b.ogg",
			"ArcaneArcher_BurstArrow-01a.ogg",
			"ArcaneArcher_Ready-01a.ogg",
			"ArcaneArcher_SleepArrow-01c.ogg",
			"Archers_Taunt-01a.ogg",
			"Archers_Taunt-02a.ogg",
			"Archers_Taunt-03e.ogg",
			"Barrack_Taunt[2]-01c.ogg",
			"Barrack_Taunt[2]-02c.ogg",
			"Barrack_Taunt[2]-03c.ogg",
			"Barrack_Taunt[2]-04e.ogg",
			"DruidHenge_Ready-01a.ogg",
			"DruidHenge_Sylvan[2]-01b.ogg",
			"GoldenBows_Crimson-01b.ogg",
			"GoldenBows_Mark-01b.ogg",
			"GoldenBows_Ready[2]-01d.ogg",
			"HighMage_ArcaneSentinel-01c.ogg",
			"HighMage_Ready-01a.ogg",
			"HighMage_Timelapse-01c.ogg",
			"Mage_Taunt-01e.ogg",
			"Mage_Taunt-03d.ogg",
			"Mage_Taunt[2]-02a.ogg",
			"PapaTree_Clobberin[2]-01e.ogg",
			"PapaTree_Fiery[2]-01d.ogg",
			"PapaTree_Ready[2]-01d.ogg",
			"StoneDruid_Taunt-01b.ogg",
			"StoneDruid_Taunt-02b.ogg",
			"StoneDruid_Taunt-03a.ogg",
			"WildMagus_Doom[2]-01b.ogg",
			"WildMagus_Ready-01a.ogg",
			"WildMagus_Silence-01c.ogg",
			"kr3_sfx_arcanearcher_sleepingarrow-op1.ogg",
			"kr3_sfx_archanearcher_arcaneexplotion_v3.ogg",
			"kr3_sfx_basicbarracks_fight.ogg",
			"kr3_sfx_basicwizard_doublebolt-op1.ogg",
			"kr3_sfx_druidhenge_bearattack_v4-op1.ogg",
			"kr3_sfx_druidhenge_beardeath_v3_op1-condesplome.ogg",
			"kr3_sfx_druidhenge_bearsummon_v3-op2.ogg",
			"kr3_sfx_druidhenge_bouldersummon.ogg",
			"kr3_sfx_druidhenge_rockthrow_v2-op2-medio.ogg",
			"kr3_sfx_druidhenge_sylvancursecast_v4-op2.ogg",
			"kr3_sfx_elvenhighmage_sentinelactivate.ogg",
			"kr3_sfx_elvenhighmage_sentinelshot_v2-op1.ogg",
			"kr3_sfx_goldenbow_arrowshot.ogg",
			"kr3_sfx_goldenbow_flarehit_v2.5.ogg",
			"kr3_sfx_goldenbow_flareshot_v2-convoz.ogg",
			"kr3_sfx_goldenbow_instakill_v2_conchime.ogg",
			"kr3_sfx_goldenbow_instakillarrowshot_v2.ogg",
			"kr3_sfx_highmage_preload_and_travel.ogg",
			"kr3_sfx_highmage_shot.ogg",
			"kr3_sfx_highmage_timecast.ogg",
			"kr3_sfx_highmage_timecastend.ogg",
			"kr3_sfx_stonedruid_boulderexplosion.ogg",
			"kr3_sfx_stonedruid_bouldersummon.ogg",
			"kr3_sfx_stonedruid_boulderthrow-op2.ogg",
			"kr3_sfx_tree_clobber_v2.ogg",
			"kr3_sfx_tree_cocoexplosion[explofuerte].ogg",
			"kr3_sfx_tree_cocothrow.ogg",
			"kr3_sfx_tree_fierynutexplotion.ogg",
			"kr3_sfx_tree_fierynutthrow.ogg",
			"kr3_sfx_tree_leaves.ogg",
			"kr3_sfx_wildmagus_boltcast_v2-op1.ogg",
			"kr3_sfx_wildmagus_disruptioncast_v2.ogg",
			"kr3_sfx_wildmagus_doomcast_v2.ogg",
			"kr3_sfx_wildmagus_doomexplotion_v3-op1.ogg",
			"kr3_sfx_wildmagus_doomloop_v2-op1.ogg"
		},
		ids = {}
	}
}
